Core/api/urls.py
from rest_framework import routers
from . import views as myapp_views

router = routers.DefaultRouter()
router.register(r'users', myapp_views.UserViewset)
router.register(r'Country', myapp_views.CountryViewset)
router.register(r'City', myapp_views.CityViewset)
router.register(r'Genre', myapp_views.GenreViewset)
router.register(r'Cast', myapp_views.CastViewset)
router.register(r'ArticleCategory', myapp_views.ArticleCategoryViewset)
router.register(r'Tag', myapp_views.TagViewset)
router.register(r'Movie', myapp_views.MovieViewset)
router.register(r'MovieGenre', myapp_views.MovieGenreViewset)
router.register(r'MoviePoster', myapp_views.MoviePosterViewset)
router.register(r'MovieTrailer', myapp_views.MovieTrailerViewset)
router.register(r'Actor', myapp_views.ActorViewset)
router.register(r'ActorMoviePoster', myapp_views.ActorMoviePosterViewset)
router.register(r'ActorMovieTrailer', myapp_views.ActorMovieTrailerViewset)
router.register(r'Comment', myapp_views.CommentViewset)
router.register(r'MovieComment', myapp_views.MovieCommentViewset)
router.register(r'Review', myapp_views.ReviewViewset)
router.register(r'MovieReview', myapp_views.MovieReviewViewset)
router.register(r'MovieCast', myapp_views.MovieCastViewset)
router.register(r'Series', myapp_views.SeriesViewset)
router.register(r'Season', myapp_views.SeasonViewset)
router.register(r'Episode', myapp_views.EpisodeViewset)
router.register(r'SeriesGenre', myapp_views.SeriesGenreViewset)
router.register(r'SeriesPoster', myapp_views.SeriesPosterViewset)
router.register(r'SeriesTrailer', myapp_views.SeriesTrailerViewset)
router.register(r'SeriesComment', myapp_views.SeriesCommentViewset)
router.register(r'SeriesCast', myapp_views.SeriesCastViewset)
router.register(r'SeriesReview', myapp_views.SeriesReviewViewset)
router.register(r'Article', myapp_views.ArticleViewset)
router.register(r'ArticleTag', myapp_views.ArticleTagViewset)
router.register(r'ArticleComment', myapp_views.ArticleCommentViewset)
router.register(r'UserFavorite', myapp_views.UserFavoriteViewset)
router.register(r'UserRate', myapp_views.UserRateViewset)


# router.register(r'relativeTypes', myapp_views.RelativeTypeViewset)
# router.register(r'patientProfiles', myapp_views.PatientProfileViewset)

Core/urls.py
from django.conf.urls import url
from . import views

app_name = 'Core'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home$', views.home, name='home'),
    url(r'^moviesingle$', views.moviesingle, name='moviesingle'),
    url(r'^moviegrid$', views.moviegrid, name='moviegrid'),
    url(r'^moviegridfw$', views.moviegridfw, name='moviegridfw'),
    url(r'^movielist$', views.movielist, name='movielist'),
    url(r'^movie/(?P<movie_id>[0-9]+)$', views.movie, name='movie-single'),
    url(r'^seriessingle$', views.seriessingle, name='seriessingle'),
    url(r'^celebritygrid$', views.celebritygrid, name='celebritygrid'),
    url(r'^celebritygridsmall$', views.celebritygridsmall, name='celebritygridsmall'),
    url(r'^celebritylist$', views.celebritylist, name='celebritylist'),
    url(r'^celebritysingle$', views.celebritysingle, name='celebritysingle'),
    url(r'^celebrity/(?P<celebrity_id>[0-9]+)$', views.celebrity, name='celebrity'),
    url(r'^bloglist$', views.bloglist, name='bloglist'),
    url(r'^bloggrid$', views.bloggrid, name='bloggrid'),
    url(r'^blogdetail/(?P<blog_id>[0-9]+)$', views.blogdetail, name='blogdetail'),
    url(r'^userfavoritegrid$', views.userfavoritegrid, name='userfavoritegrid'),
    url(r'^userfavoritelist$', views.userfavoritelist, name='userfavoritelist'),
    url(r'^userprofile$', views.userprofile, name='userprofile'),
    url(r'^userrate$', views.userrate, name='userrate'),
    url(r'^page404$', views.page404, name='page404'),
    url(r'^comingsoon$', views.comingsoon, name='comingsoon'),
    url(r'^feed$', views.feed, name='feed'),
]

Core/api/views.py
from rest_framework import viewsets, permissions
from django.db.models import Q
from rest_framework.pagination import PageNumberPagination
from django.contrib.auth.models import User
from Core import models
from . import serializer


class StandardResultsSetPagination(PageNumberPagination):
    page_size = 50
    page_size_query_param = 'page_size'
    max_page_size = 200


class CountryViewset(viewsets.ModelViewSet):
    queryset = models.Country.objects.all()
    serializer_class = serializer.CountrySerializer
    pagination_class = StandardResultsSetPagination
    permission_classes = [permissions.IsAuthenticatedOrReadOnly,]

    def get_queryset(self):
        qs = super().get_queryset().order_by('-id')
        query = self.request.GET.get("q")
        if query is not None:
            qs = qs.filter(
                Q(title__icontains=query)
                | Q(title_en__icontains=query)
            ).distinct()
        return qs


class UserViewset(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = serializer.UserSerializer
    pagination_class = StandardResultsSetPagination
    permission_classes = [permissions.IsAuthenticatedOrReadOnly,]

    def get_queryset(self):
        qs = super().get_queryset().order_by('-date_joined')
        query = self.request.GET.get("q")
        if query is not None:
            qs = qs.filter(
                Q(username__icontains=query)
                | Q(first_name__icontains=query)
                | Q(last_name__icontains=query)
                | Q(email__icontains=query)
            ).distinct()
        return qs


class CityViewset(viewsets.ModelViewSet):
    queryset = models.City.objects.all()
    serializer_class = serializer.CitySerializer
    pagination_class = StandardResultsSetPagination
    permission_classes = [permissions.IsAuthenticatedOrReadOnly,]

    def get_queryset(self):
        qs = super().get_queryset().order_by('-id')
        query = self.request.GET.get("q")
        if query is not None:
            qs = qs.filter(
                Q(title__icontains=query)
                | Q(title_en__icontains=query)
            ).distinct()
        return qs


class GenreViewset(viewsets.ModelViewSet):
    queryset = models.Genre.objects.all()
    serializer_class = serializer.GenreSerializer
    pagination_class = StandardResultsSetPagination
    permission_classes = [permissions.IsAuthenticatedOrReadOnly,]

    def get_queryset(self):
        qs = super().get_queryset().order_by('-id')
        query = self.request.GET.get("q")
        if query is not None:
            qs = qs.filter(
                Q(title__icontains=query)
                | Q(title_en__icontains=query)
            ).distinct()
        return qs


class CastViewset(viewsets.ModelViewSet):
    queryset = models.Cast.objects.all()
    serializer_class = serializer.CastSerializer
    pagination_class = StandardResultsSetPagination
    permission_classes = [permissions.IsAuthenticatedOrReadOnly,]

    def get_queryset(self):
        qs = super().get_queryset().order_by('-id')
        query = self.request.GET.get("q")
        if query is not None:
            qs = qs.filter(
                Q(title__icontains=query)
                | Q(title_en__icontains=query)
            ).distinct()
        return qs


class ArticleCategoryViewset(viewsets.ModelViewSet):
    queryset = models.ArticleCategory.objects.all()
    serializer_class = serializer.ArticleCategorySerializer
    pagination_class = StandardResultsSetPagination
    permission_classes = [permissions.IsAuthenticatedOrReadOnly,]

    def get_queryset(self):
        qs = super().get_queryset().order_by('-id')
        query = self.request.GET.get("q")
        if query is not None:
            qs = qs.filter(
                Q(title__icontains=query)
                | Q(title_en__icontains=query)
            ).distinct()
        return qs


class TagViewset(viewsets.ModelViewSet):
    queryset = models.Tag.objects.all()
    serializer_class = serializer.TagSerializer
    pagination_class = StandardResultsSetPagination
    permission_classes = [permissions.IsAuthenticatedOrReadOnly,]

    def get_queryset(self):
        qs = super().get_queryset().order_by('-id')
        query = self.request.GET.get("q")
        if query is not None:
            qs = qs.filter(
                Q(title__icontains=query)
                | Q(title_en__icontains=query)
            ).distinct()
        return qs


class MovieViewset(viewsets.ModelViewSet):
    queryset = models.Movie.objects.all()
    # serializer_class = serializer.MovieSerializer
    pagination_class = StandardResultsSetPagination
    permission_classes = [permissions.IsAuthenticatedOrReadOnly,]

    def get_serializer_class(self):
        if self.action == 'list':
            return serializer.MovieSerializer
        if self.action == 'retrieve':
            return serializer.MovieDetailSerializer
        return serializer.MovieSerializer  # create/destroy/update.

    def get_queryset(self):
        qs = super().get_queryset().order_by('-id')

        # Order
        query = self.request.GET.get("ordered_by")
        if query is not None:
            if query == "download_count":
                qs = qs.order_by('-download_count')
            elif query == "view_count":
                qs = qs.order_by('-view_count')
            elif query == "vote_count":
                qs = qs.order_by('-vote_count')
            elif query == "latest":
                qs = qs.order_by('-created_on')
            else:
                qs = qs.order_by('-id')

        # search
        query = self.request.GET.get("q")
        if query is not None:
            qs = qs.filter(
                Q(title__icontains=query)
                | Q(title_en__icontains=query)
            ).distinct()
        # Genre
        query = self.request.GET.get("genre")
        if query is not None:
            qs = qs.filter(
                Q(movieGenre__genre__title=query)
            ).distinct()
        # Rate
        query = self.request.GET.get("rate")
        if query is not None:
            qs = qs.filter(
                Q(rate=query)
            ).distinct()
        # Date
        query_date_from = self.request.GET.get("date_from")
        query_date_to = self.request.GET.get("date_to")
        if query_date_from is not None:
            qs = qs.filter(
                Q(created_on__gte=query_date_from)
            ).distinct()
        if query_date_to is not None:
            qs = qs.filter(
                Q(created_on__lte=query_date_to)
            ).distinct()
        # if query_date_from is not None and query_date_to is not None:
        #     qs = qs.filter(
        #         Q(created_on__range=[query_date_from, query_date_to])
        #     ).distinct()
        return qs


class MovieGenreViewset(viewsets.ModelViewSet):
    queryset = models.MovieGenre.objects.all()
    serializer_class = serializer.MovieGenreSerializer
    pagination_class = StandardResultsSetPagination
    permission_classes = [permissions.IsAuthenticatedOrReadOnly,]

    def get_queryset(self):
        qs = super().get_queryset().order_by('-id')
        return qs


class MoviePosterViewset(viewsets.ModelViewSet):
    queryset = models.MoviePoster.objects.all()
    serializer_class = serializer.MoviePosterSerializer
    pagination_class = StandardResultsSetPagination
    permission_classes = [permissions.IsAuthenticatedOrReadOnly,]

    def get_queryset(self):
        qs = super().get_queryset().order_by('-id')
        return qs


class MovieTrailerViewset(viewsets.ModelViewSet):
    queryset = models.MovieTrailer.objects.all()
    serializer_class = serializer.MovieTrailerSerializer
    pagination_class = StandardResultsSetPagination
    permission_classes = [permissions.IsAuthenticatedOrReadOnly,]

    def get_queryset(self):
        qs = super().get_queryset().order_by('-id')
        return qs


class ActorViewset(viewsets.ModelViewSet):
    queryset = models.Actor.objects.all()
    # serializer_class = serializer.ActorSerializer
    pagination_class = StandardResultsSetPagination
    permission_classes = [permissions.IsAuthenticatedOrReadOnly,]

    def get_serializer_class(self):
        if self.action == 'list':
            return serializer.ActorSerializer
        if self.action == 'retrieve':
            return serializer.ActorDetailSerializer
        return serializer.ActorSerializer  # create/destroy/update.

    def get_queryset(self):
        qs = super().get_queryset()

        # order
        query = self.request.GET.get("order")
        if query is not None:
            if query == "محبوبیت":
                qs.order_by('-download_count')
            if query == "بازدید":
                qs.order_by('-view_count')
            if query == "تولد":
                print('-birthDay')
                qs.order_by('-birthDay')
            else:
                qs.order_by('-id')


        # search
        query = self.request.GET.get("q")
        if query is not None:
            qs = qs.filter(
                Q(name__icontains=query)
                | Q(name_en__icontains=query)
                | Q(family__icontains=query)
                | Q(family_en__icontains=query)
            ).distinct()

        # alphabet
        query = self.request.GET.get("alphabet")
        if query is not None:
            qs = qs.filter(
                Q(name__startswith=query)
                | Q(name_en__startswith=query)
                | Q(family__startswith=query)
                | Q(family_en__startswith=query)
            ).distinct()

        # cast
        query = self.request.GET.get("cast")
        if query is not None:
            qs = qs.filter(
                Q(movieCasts__cast__title=query)
            ).distinct()

        # Date
        query_date_from = self.request.GET.get("date_from")
        query_date_to = self.request.GET.get("date_to")
        if query_date_from is not None:

Core/templates/Core/Utils/Ads.html
{% load static %}
<div class="ads">
    <img src="{% static 'Core/images/fajr1.jpg' %}" alt="">
</div>

Core/templates/Core/Utils/SideBar.html
{% load static %}
<div class="sidebar">
    <div class="searh-form">
        <h4 class="sb-title">جست و جو بازیگران</h4>
        <form class="form-style-1 celebrity-form" action="#">
            <div class="row">
                <!-- Celebrity name -->
                <div class="col-md-12 form-it">
                    <label>نام بازیگر</label>
                    <input id="celebrity-search" type="text" placeholder="کلیدواژه ها را وارد کنید">
                </div>
                <!-- Celebrity Letter -->
                <div class="col-md-12 form-it">
                    <label>الفبا</label>
                    <select id="select-actor-alphabet">
                        {% include 'Core/Utils/alphabet.html' %}
                    </select>
                </div>
                <!-- Category -->
                <div class="col-md-12 form-it">
                    <label>دسته بندی</label>
                    <select id="select-actor-cast">
                        <option value="همه">همه</option>
                        {% for cast in casts %}
                            <option value="{{ cast.title }}">{{ cast.title }}</option>
                        {% endfor %}

                    </select>
                </div>
                <!-- Year of birth -->
                <div class="col-md-12 form-it">
                    <label>تاریخ تولد</label>
                    <div class="row">
                        <div class="col-md-6">
                            <select id="select-actor-birthday-start">
                                <option value="range">1970</option>
                                <option value="number">Other</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <select id="select-actor-birthday-end">
                                <option value="range">1990</option>
                                <option value="number">others</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 ">
                    <input class="submit" type="submit" value="فیلتر" onclick="event.preventDefault(); filterActor()">
                </div>
            </div>
        </form>
    </div>
    {% include 'Core/Utils/Ads.html' %}
    <div class="celebrities">
        <h4 class="sb-title">featured celebrity</h4>
        <div class="celeb-item">
            <a href="#"><img src="{% static 'Core/images/uploads/ava1.jpg' %}" alt=""></a>
            <div class="celeb-author">
                <h6><a href="#">Samuel N. Jack</a></h6>
                <span>Actor</span>
            </div>
        </div>
        <div class="celeb-item">
            <a href="#"><img src="{% static 'Core/images/uploads/ava2.jpg' %}" alt=""></a>
            <div class="celeb-author">
                <h6><a href="#">Benjamin Carroll</a></h6>
                <span>Actor</span>
            </div>
        </div>
        <div class="celeb-item">
            <a href="#"><img src="{% static 'Core/images/uploads/ava3.jpg' %}" alt=""></a>
            <div class="celeb-author">
                <h6><a href="#">Beverly Griffin</a></h6>
                <span>Actor</span>
            </div>
        </div>
        <div class="celeb-item">
            <a href="#"><img src="{% static 'Core/images/uploads/ava4.jpg' %}" alt=""></a>
            <div class="celeb-author">
                <h6><a href="#">Justin Weaver</a></h6>
                <span>Actor</span>
            </div>
        </div>
    </div>
</div>

Core/templates/Core/Utils/SideBarMovie.html
{% load static %}
<div class="sidebar">
    <div class="searh-form">
        <h4 class="sb-title">جست و جو فیلم</h4>
        <form class="form-style-1 celebrity-form" action="#">
            <div class="row">
                <!-- Celebrity name -->
                <div class="col-md-12 form-it">
                    <label>نام فیلم</label>
                    <input id="celebrity-search" type="text" placeholder="کلیدواژه ها را وارد کنید">
                </div>
                <!-- Celebrity Letter -->
                <div class="col-md-12 form-it">
                    <label>ژانر</label>
                    <select id="select-actor-alphabet">
                        {% include 'Core/Utils/alphabet.html' %}
                    </select>
                </div>
                <!-- Category -->
                <div class="col-md-12 form-it">
                    <label>نمره</label>
                    <select id="select-actor-cast">
                        <option value="همه">همه</option>
                        {% for cast in casts %}
                            <option value="{{ cast.title }}">{{ cast.title }}</option>
                        {% endfor %}

                    </select>
                </div>
                <!-- Year of birth -->
                <div class="col-md-12 form-it">
                    <label>تاریخ</label>
                    <div class="row">
                        <div class="col-md-6">
                            <select id="select-actor-birthday-start">
                                <option value="range">1970</option>
                                <option value="number">Other</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <select id="select-actor-birthday-end">
                                <option value="range">1990</option>
                                <option value="number">others</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 ">
                    <input class="submit" type="submit" value="فیلتر" onclick="event.preventDefault(); filterActor()">
                </div>
            </div>
        </form>
    </div>
    {% include 'Core/Utils/Ads.html' %}

</div>

Core/templates/Core/Utils/alphabet.html
<option value="همه">همه</option>
<option value="ا">ا</option>
<option value="ب">ب</option>
<option value="پ">پ</option>
<option value="ت">ت</option>
<option value="ج">ج</option>
<option value="چ">چ</option>
<option value="ح">ح</option>
<option value="خ">خ</option>
<option value="د">د</option>
<option value="ذ">ذ</option>
<option value="ر">ر</option>
<option value="ز">ز</option>
<option value="ژ">ژ</option>
<option value="س">س</option>
<option value="ش">ش</option>
<option value="ص">ص</option>
<option value="ض">ض</option>
<option value="ط">ط</option>
<option value="ظ">ظ</option>
<option value="ع">ع</option>
<option value="غ">غ</option>
<option value="ف">ف</option>
<option value="ق">ق</option>
<option value="ک">ک</option>
<option value="گ">گ</option>
<option value="ل">ل</option>
<option value="م">م</option>
<option value="ن">ن</option>
<option value="و">و</option>
<option value="ه">ه</option>
<option value="ی">ی</option>

Core/templates/Core/Utils/footBar.html
{% load static %}

<div class="topbar-filter" dir="rtl">

    <label>بازیگران در هر صفحه:</label>

    <select id="select-actor-count" dir="ltr" style="font-family: 'IRANSansNum'">
        <option value="25">25 بازیگر</option>
        <option value="50">50 بازیگر</option>
        <option value="100">100 بازیگر</option>
        <option value="250">250 بازیگر</option>
    </select>

    <div class="pagination2" dir="ltr">
                            <span id="pagination-celebrity-smallgrid" style="font-family: IRANSansNum">
                                <a class="active" href="#">1</a>
                                <a href="#">2</a>
                                <a href="#">3</a>
                                <a href="#">4</a>
                                <a href="#">5</a>
                                <a href="#">6</a>
                                <a href="#"><i class="ion-arrow-right-b"></i></a>
                            </span>
        <span id="pagination-celebrity-smallgrid-title" style="font-family: IRANSansNum">Page 1 of 6:</span>
    </div>
</div>

Core/templates/Core/Utils/head.html
{% load static %}

    <div class="hero common-hero">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="hero-ct">
                        <h1>{{ page_title }}</h1>
                        <ul class="breadcumb">
                            <li> {{ page_url }} <span class="ion-ios-arrow-left"></span> </li>
                            <li class="active"><a href="{% url 'Core:index' %}">خانه</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

Core/templates/Core/Utils/login.html
{% load static %}

<div class="login-wrapper" id="login-content">
    <div class="login-content">
        <a href="#" class="close">x</a>
        <h3>Login</h3>
        <form method="post" action="#">
            <div class="row">
                <label for="username">
                    Username:
                    <input type="text" name="username" id="username" placeholder="Hugh Jackman" pattern="^[a-zA-Z][a-zA-Z0-9-_\.]{8,20}$" required="required" />
                </label>
            </div>

            <div class="row">
                <label for="password">
                    Password:
                    <input type="password" name="password" id="password" placeholder="******" pattern="(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$" required="required" />
                </label>
            </div>
            <div class="row">
                <div class="remember">
                    <div>
                        <input type="checkbox" name="remember" value="Remember me"><span>Remember me</span>
                    </div>
                    <a href="#">Forget password ?</a>
                </div>
            </div>
            <div class="row">
                <button type="submit">Login</button>
            </div>
        </form>
        <div class="row">
            <p>Or via social</p>
            <div class="social-btn-2">
                <a class="fb" href="#"><i class="ion-social-facebook"></i>Facebook</a>
                <a class="tw" href="#"><i class="ion-social-twitter"></i>twitter</a>
            </div>
        </div>
    </div>
</div>

Core/templates/Core/Utils/reviewStar.html
{% load static %}

<div class="no-star">
    <i class="ion-android-star"></i>
    <i class="ion-android-star"></i>
    <i class="ion-android-star"></i>
    <i class="ion-android-star"></i>
    <i class="ion-android-star"></i>
    <i class="ion-android-star"></i>
    <i class="ion-android-star"></i>
    <i class="ion-android-star"></i>
    <i class="ion-android-star"></i>
    <i class="ion-android-star last"></i>
</div>

Core/templates/Core/Utils/signup.html
{% load static %}

<div class="login-wrapper"  id="signup-content">
    <div class="login-content">
        <a href="#" class="close">x</a>
        <h3>sign up</h3>
        <form method="post" action="#">
            <div class="row">
                <label for="username-2">
                    Username:
                    <input type="text" name="username" id="username-2" placeholder="Hugh Jackman" pattern="^[a-zA-Z][a-zA-Z0-9-_\.]{8,20}$" required="required" />
                </label>
            </div>

            <div class="row">
                <label for="email-2">
                    your email:
                    <input type="password" name="email" id="email-2" placeholder="" pattern="(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$" required="required" />
                </label>
            </div>
            <div class="row">
                <label for="password-2">
                    Password:
                    <input type="password" name="password" id="password-2" placeholder="" pattern="(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$" required="required" />
                </label>
            </div>
            <div class="row">
                <label for="repassword-2">
                    re-type Password:
                    <input type="password" name="password" id="repassword-2" placeholder="" pattern="(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$" required="required" />
                </label>
            </div>
            <div class="row">
                <button type="submit">sign up</button>
            </div>
        </form>
    </div>
</div>

Core/templates/Core/Utils/spolightActrs.html
{% load static %}

<div class="celebrities" dir="rtl">
    <h4 class="sb-title">هنرمندان فعال</h4>

    {% for spolight_actor in spolight_actors %}
        <div class="celeb-item">
            <a href="{% url 'Core:celebrity' spolight_actor.actor_id %}"><img src="{{ spolight_actor.actor.thumbnail.url }}" alt="" style="width: 70px; height: 70px; object-fit: cover"></a>
            <div class="celeb-author">
                <h6><a href="#">{{ spolight_actor.actor.name }} {{ spolight_actor.actor.family }}</a></h6>
                <span>
                                            {% for cast in spolight_actor.actor.movieCasts.all %}
                                                {{ cast.cast.title }},
                                            {% endfor %}
                                        </span>
            </div>
        </div>
    {% endfor %}

    <a href="#" class="btn">مشاهده تمامی بازیگران<i class="ion-ios-arrow-left"></i></a>
</div>

Core/templates/Core/Utils/topBar.html
{% load static %}

<div class="topbar-filter" dir="rtl">

    <p class="pad-change">تعداد بازیگرها: <span id="actor-count">1,608</span></p>
    <label>مرتب سازی:</label>
    <select id="celebrity-select-sort" dir="ltr">
        <option value="محبوبیت">محبوبیت</option>
        <option value="بازدید">بازدید</option>
        <option value="تولد">تاریخ تولد</option>
    </select>
    <a href="{% url 'Core:celebritylist' %}" class="list"><i class="ion-ios-list-outline {% if page_url_en == "celebrity-list" %}active{% endif %}"></i></a>
    <a href="{% url 'Core:celebritygrid' %}" class="grid"><i class="ion-ios-grid-view-outline {% if page_url_en == "celebrity-grid" %}active{% endif %}"></i></a>
    <a href="{% url 'Core:celebritygridsmall' %}" class="grid" style="border-right: 1px solid #405266;"><i class="ion-grid {% if page_url_en == "celebrity-grid-small" %}active{% endif %}"></i></a>
</div>